### ISSUE TITLE
Feature Request gamevfs

### ISSUE THREAD

**Issue by TobyKaos** [clanofthecloud/javascript-sdk#1]
En attendant l'ajout du gamevfs dans le script coffee on peut rajouter ceci ligne 8929 du bundle.js

gamevfs: function(domain, key, cb) {
      if (key == null) {
        key = '';
      }
      return agent.get("/v1/vfs/" + domain + "/" + key).use(prefixer).set(appCredentials).end(function(err, res) {
        if (err != null) {
          return cb(err);
        } else {
          if (res.error) {
            return cb(new ClanError(res.status, res.body));
          } else {
            return cb(null, res.body);
          }
        }
      });

```
},
```

**Comment by Rolandvl** [comment]
game.vfs added !
